#!/usr/bin/bash

TMPDIR=tmp_openvpn_pia
SERVERLIST=servers.txt
IPTABLESVPNPATH=/home/fs0/prg/shell-scripts/iptablesVPN

mkdir $TMPDIR
cd $TMPDIR

wget -q https://www.privateinternetaccess.com/openvpn/openvpn-ip.zip
unzip -qq openvpn-ip.zip
grep -h remote\  *.ovpn | cut -d' ' -f2 > $SERVERLIST

echo "#!/usr/bin/bash" > $IPTABLESVPNPATH

# flush
echo "iptables -F" >> $IPTABLESVPNPATH

# default chain policies
echo "iptables -P INPUT DROP" >> $IPTABLESVPNPATH
echo "iptables -P FORWARD DROP" >> $IPTABLESVPNPATH
echo "iptables -P OUTPUT DROP" >> $IPTABLESVPNPATH
echo "ip6tables -P INPUT DROP" >> $IPTABLESVPNPATH
echo "ip6tables -P FORWARD DROP" >> $IPTABLESVPNPATH
echo "ip6tables -P OUTPUT DROP" >> $IPTABLESVPNPATH


# accept any packet from established or related connections
echo "iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT" >> $IPTABLESVPNPATH

# only allow tun interface and localhost
echo "iptables -A INPUT -i tun+ -j ACCEPT" >> $IPTABLESVPNPATH
echo "iptables -A OUTPUT -o tun+ -j ACCEPT" >> $IPTABLESVPNPATH 
echo "iptables -A INPUT -s 127.0.0.1 -j ACCEPT" >> $IPTABLESVPNPATH 
echo "iptables -A OUTPUT -d 127.0.0.1 -j ACCEPT" >> $IPTABLESVPNPATH 

# allow PIA servers
for server in `cat $SERVERLIST`
do
   echo "iptables -A INPUT -s" $server "-j ACCEPT" >> $IPTABLESVPNPATH 
   echo "iptables -A OUTPUT -d" $server "-j ACCEPT" >> $IPTABLESVPNPATH 
done

# allow icmp
echo "iptables -A INPUT -p icmp -m conntrack --ctstate NEW -j ACCEPT" >> $IPTABLESVPNPATH

# allow local irc
echo "iptables -A INPUT -p tcp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 6667 -j ACCEPT" >> $IPTABLESVPNPATH
echo "iptables -A INPUT -p tcp -s 127.0.0.1 -m conntrack --ctstate NEW --dport 6667 -j ACCEPT" >> $IPTABLESVPNPATH

# allow local ssh
echo "iptables -A INPUT -p tcp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 22 -j ACCEPT" >> $IPTABLESVPNPATH

# allow android xbmc remote
echo "iptables -A INPUT -p tcp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 8080 -j ACCEPT" >> $IPTABLESVPNPATH
echo "iptables -A INPUT -p udp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 9777 -j ACCEPT" >> $IPTABLESVPNPATH

# allow local mpd
echo "iptables -A INPUT -p tcp -s 127.0.0.1 -m conntrack --ctstate NEW --dport 6600 -j ACCEPT" >> $IPTABLESVPNPATH

# drop everything else
echo "iptables -A INPUT -j DROP" >> $IPTABLESVPNPATH 
echo "ip6tables -A INPUT -j DROP" >> $IPTABLESVPNPATH 

# allow any local traffic that comes from this server
echo "iptables -A OUTPUT -d 192.168.178.0/24 -m conntrack --ctstate NEW,ESTABLISHED,RELATED -j ACCEPT" >> $IPTABLESVPNPATH

# drop everything else
echo "iptables -A OUTPUT -j DROP" >> $IPTABLESVPNPATH 
echo "ip6tables -A OUTPUT -j DROP" >> $IPTABLESVPNPATH 

# save rules
echo "iptables-save > /etc/iptables/iptables.rules" >> $IPTABLESVPNPATH
echo "ip6tables-save > /etc/iptables/ip6tables.rules" >> $IPTABLESVPNPATH

# restart iptables just in case
echo "systemctl restart iptables.service" >> $IPTABLESVPNPATH
echo "systemctl restart ip6tables.service" >> $IPTABLESVPNPATH

echo "systemctl status iptables.service" >> $IPTABLESVPNPATH
echo "systemctl status ip6tables.service" >> $IPTABLESVPNPATH

cd ..
rm -rf $TMPDIR
