#! /bin/bash

# delete all existing rules
iptables -F
ip6tables -F

# set default chain policies
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP
ip6tables -P INPUT DROP
ip6tables -P FORWARD DROP
ip6tables -P OUTPUT DROP


# INPUT

# accept any packet from established or related connections
iptables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT
ip6tables -A INPUT -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# allow local ftp
#iptables -A INPUT -p tcp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 21 -j ACCEPT
#iptables -A INPUT -p tcp -s 127.0.0.1 -m conntrack --ctstate NEW --dport 21 -j ACCEPT
#allow ftp
#iptables -A INPUT -p tcp -m conntrack --ctstate NEW --dport 21 -j ACCEPT

# allow icmp
iptables -A INPUT -p icmp -m conntrack --ctstate NEW -j ACCEPT

# allow local irc
iptables -A INPUT -p tcp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 6667 -j ACCEPT
iptables -A INPUT -p tcp -s 127.0.0.1 -m conntrack --ctstate NEW --dport 6667 -j ACCEPT
ip6tables -A INPUT -p tcp -s 2a02:8070:f11c:fb00::/56 -m conntrack --ctstate NEW --dport 6667 -j ACCEPT
ip6tables -A INPUT -p tcp -s ::1 -m conntrack --ctstate NEW --dport 6667 -j ACCEPT
# allow irc
#iptables -A INPUT -p tcp -m conntrack --ctstate NEW --dport 6667 -j ACCEPT
#ip6tables -A INPUT -p tcp -m conntrack --ctstate NEW --dport 6667 -j ACCEPT

# allow local ssh
iptables -A INPUT -p tcp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 22 -j ACCEPT
# allow ssh
#iptables -A INPUT -p tcp -m conntrack --ctstate NEW --dport 22 -j ACCEPT

# allow local udp-stream
#iptables -A INPUT -p udp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 1234 -j ACCEPT

# allow local http stream (android xbmc remote control)
iptables -A INPUT -p tcp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 8080 -j ACCEPT
# allow http stream
#iptables -A INPUT -p tcp -m conntrack --ctstate NEW --dport 8080 -j ACCEPT

# android xbmc remote control
iptables -A INPUT -p udp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 9777 -j ACCEPT

# allow steam
iptables -A INPUT -p tcp -m conntrack --ctstate NEW --dport 57343 -j ACCEPT
#iptables -A INPUT -p udp -m conntrack --ctstate NEW --dport 27000:65535 -j ACCEPT
#iptables -A INPUT -p tcp -m conntrack --ctstate NEW --dport 27000:65535 -j ACCEPT

# allow local BOINC
#iptables -A INPUT -p tcp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 31416 -j ACCEPT
#iptables -A INPUT -p tcp -s 127.0.0.1 -m conntrack --ctstate NEW --dport 31416 -j ACCEPT

# allow local minecraft
iptables -A INPUT -p tcp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 25565 -j ACCEPT
# allow minecraft
#iptables -A INPUT -p tcp -m conntrack --ctstate NEW --dport 25565 -j ACCEPT

# allow teamspeak
#iptables -A INPUT -p tcp -m conntrack --ctstate NEW --dport 10011 -j ACCEPT
#iptables -A INPUT -p udp -m conntrack --ctstate NEW --dport 9987 -j ACCEPT

# allow quake 3 arena
#iptables -A INPUT -p udp -m conntrack --ctstate NEW --dport 27960 -j ACCEPT

# allow bittorrent
#iptables -A INPUT -p tcp -m conntrack --ctstate NEW --dport 51413 -j ACCEPT
#ip6tables -A INPUT -p tcp -m conntrack --ctstate NEW --dport 51413 -j ACCEPT

# allow local mpd
iptables -A INPUT -p tcp -s 127.0.0.1 -m conntrack --ctstate NEW --dport 6600 -j ACCEPT

# drop everything else
iptables -A INPUT -j DROP
ip6tables -A INPUT -j DROP


# OUTPUT

# allow any traffic that comes from this server
iptables -A OUTPUT -m conntrack --ctstate NEW,ESTABLISHED,RELATED -j ACCEPT
ip6tables -A OUTPUT -m conntrack --ctstate NEW,ESTABLISHED,RELATED -j ACCEPT


# save rules
iptables-save > /etc/iptables/iptables.rules
ip6tables-save > /etc/iptables/ip6tables.rules

# restart iptables just in case
systemctl restart iptables.service
systemctl restart ip6tables.service

systemctl status iptables.service
systemctl status ip6tables.service
