#!/usr/bin/bash

VPN=37.48.81.8

# flush
iptables -F
ip6tables -F

# default chain policies
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT DROP
ip6tables -P INPUT DROP
ip6tables -P FORWARD DROP
ip6tables -P OUTPUT DROP

# accept any local packet from established or related connections
iptables -A INPUT -d 192.168.178.0/24 -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# only allow tun interface and localhost
iptables -A INPUT -i tun+ -j ACCEPT
iptables -A INPUT -s 127.0.0.1 -j ACCEPT
iptables -A OUTPUT -o tun+ -j ACCEPT
iptables -A OUTPUT -d 127.0.0.1 -j ACCEPT

# allow vpn server
iptables -A INPUT -p udp -s $VPN -j ACCEPT
iptables -A OUTPUT -p udp -d $VPN -j ACCEPT

# allow icmp
iptables -A INPUT -p icmp -m conntrack --ctstate NEW -j ACCEPT

# allow local irc
iptables -A INPUT -p tcp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 6667 -j ACCEPT
iptables -A INPUT -p tcp -s 127.0.0.1 -m conntrack --ctstate NEW --dport 6667 -j ACCEPT

# allow local ssh
iptables -A INPUT -p tcp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 22 -j ACCEPT

# allow android xbmc remote
iptables -A INPUT -p tcp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 8080 -j ACCEPT
iptables -A INPUT -p udp -s 192.168.178.0/24 -m conntrack --ctstate NEW --dport 9777 -j ACCEPT

# allow local mpd
iptables -A INPUT -p tcp -s 127.0.0.1 -m conntrack --ctstate NEW --dport 6600 -j ACCEPT

# allow any local traffic that comes from this server
iptables -A OUTPUT -d 192.168.178.0/24 -m conntrack --ctstate NEW,ESTABLISHED,RELATED -j ACCEPT

# drop everything else
iptables -A INPUT -j DROP
iptables -A OUTPUT -j DROP

# save rules
iptables-save > /etc/iptables/iptables.rules
ip6tables-save > /etc/iptables/ip6tables.rules

# restart iptables just in case
systemctl restart iptables.service
systemctl restart ip6tables.service

systemctl status iptables.service
systemctl status ip6tables.service
